server:
  port: 8888
# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  # FREEMARKER (FreeMarkerAutoConfiguration)
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/ #comma-separated list

  web:
    resources:
      static-locations: classpath:/static/

  jackson:
    #    generator:
    #      write_numbers_as_strings: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: NON_NULL
  #    serialization:
  #      write_bigdecimal_as_plain: true

  # AI https://docs.spring.io/spring-ai/reference/api/mcp/mcp-server-boot-starter-docs.html
  ai:
    mcp:
      server:
        enabled: true
        stdio: false
        name: options-trade-mcp-server
        version: 1.0.0
        type: SYNC
        tool-change-notification: true
        capabilities:
          resource: false
          tool: true
          prompt: false
          completion: false
        sse-message-endpoint: /mcp/message
        sse-endpoint: /sse
        request-timeout: 30

# JobRunr
org:
  jobrunr:
    background-job-server:
      enabled: true
      worker-count: 1
      poll-interval-in-seconds: 30
      delete-succeeded-jobs-after: 8760h
      permanently-delete-deleted-jobs-after: 8760h
    dashboard:
      enabled: true

# 应用自定义配置
options-trade:
  default-owner: qiyan
  cookie:
    maxAgeDays: 30

# 日志配置
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 7
    total-size-cap: 50MB